  eureka:
   client:
      fetch-registry: false
      register-with-eureka: false
  server:
    port: 8761


















#   client:
#      fetch-registry: false
#      register-with-eureka: false
#server:
#    port: 8761